# config/cable.yml
production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable

development:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable

test:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable