# config/queue.yml
production:
  worker:
    queues:
      - default
      - mailers
  worker_pool:
    queues:
      - default
      - mailers
    threads: 3
    processes: 1

development:
  worker:
    queues:
      - default
      - mailers
  worker_pool:
    queues:
      - default
      - mailers
    threads: 3
    processes: 1

test:
  worker:
    queues:
      - default
      - mailers
  worker_pool:
    queues:
      - default
      - mailers
    threads: 3
    processes: 1